kind: ConfigMap
apiVersion: v1
metadata:
  name: springmusic-configmap
  namespace: vitess
data:
  # Or set as complete file contents (even JSON!)
  keys: |
    db.address=localhost
    db.port=3306
    db.user=user
    db.password=q1w2e3